#!/bin/bash

ENV_NAME=translate_env

module load python/3.6
conda create --name=$ENV_NAME python=3.6 ipykernel
source activate $ENV_NAME
ipython kernel install --user --name $ENV_NAME
pip install --upgrade google-cloud-translate nltk google-api-python-client google-auth-httplib2 oauth2client
